version: '3.8'

services:
  wordpress:
    image: ttyeri/woocommerce:latest
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_PORT: 3306
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass1
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_URL: http://localhost:8080
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: admin1234
      WORDPRESS_ADMIN_EMAIL: admin@example.com
    volumes:
      - wp_data:/var/www/html
      #- ./wp-content:/var/www/html/wp-content

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass1
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass1
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wp_data:
  db_data:
